### ISSUE TITLE
Find All: clicking on a search result doesn't always bring it within current window.

### ISSUE THREAD

**Issue by darthschmoo** [deplorableword/textmate-solarized#63]
Steps: 

1) Open a Find dialog in a project (Cmd-Shift-F).
2) Search for something common.  "the" for example.
3) Click one of the results found by the dialog.

It opens up the page that contains the result and highlights the text, but it doesn't seem to scroll to put the highlighted text into the visible window.  Sometimes clicking the result a second time will center the text in the visible window (other times it seems to misfire).  But that seems like it ought to happen on the first click.  At least, whatever it's doing now feels counterintuitive.

**Comment by darthschmoo** [comment]
H

**Comment by darthschmoo** [comment]
I just realized that this is the bugtracker for one of the themes, not for Textmate2 itself.  Sorry.

**Comment by deplorableword** [comment]
No worries :) I wished I had the power to fix this

On Monday, 16 February 2015, Bryce Anderson <notifications@github.com>
wrote:

> I just realized that this is the bugtracker for one of the themes, not for
> Textmate2 itself. Sorry.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deplorableword/textmate-solarized/issues/63#issuecomment-74450296>
> .
>


-- 
Tom Martin
twitter.com/deplorableword
devart.org
